# Generated by Django 5.2.4 on 2026-03-03 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_seed_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("next_billing_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("trial", "Trial"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(default="#9C27B0", max_length=7)),
                ("notify_before_renewal", models.PositiveSmallIntegerField(default=3)),
                ("auto_create_transaction", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("started_date", models.DateField(blank=True, null=True)),
                ("cancelled_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["next_billing_date"],
            },
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="finance_tra_account_588697_idx",
            old_name="finance_tra_account_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="finance_tra_categor_e54d5a_idx",
            old_name="finance_tra_categor_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="finance_tra_transac_a36dff_idx",
            old_name="finance_tra_transac_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="finance_tra_created_f0aa0b_idx",
            old_name="finance_tra_created_idx",
        ),
        migrations.AddField(
            model_name="subscription",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="finance.category",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
